name: micropython
version: "1.9.4"
summary: MicroPython
description: >
    MicroPython is a lean and efficient Python implementation for microcontrollers and constrained systems.

grade: devel
confinement: devmode

apps:
    micropython:
        command: micropython
parts:
    micropython:
        plugin: micropython-make
        artifacts:
            - micropython
        source: https://github.com/micropython/micropython/releases/download/v1.9.4/micropython-1.9.4.tar.gz
        source-subdir: ports/unix
        source-type: tar
