name: micropython
version: "1.19"
summary: MicroPython linux version
description: |
  MicroPython is a lean and efficient Python implementation for microcontrollers and constrained systems.

base: core20
confinement: strict
grade: stable

apps:
  micropython:
    command: usr/local/bin/micropython
    plugs:
      - home
      - network

build-packages:
  - build-essential
  - libffi-dev
  - pkg-config

parts:
  micropython:
    plugin: make
    source: https://github.com/micropython/micropython/releases/download/v1.19/micropython-1.19.tar.xz
    source-type: tar
    source-subdir: ports/unix
  desktop:
    plugin: dump
    source: snap/gui
