name: micropython
version: "1.9.4"
summary: MicroPython
description: |
    MicroPython is a lean and efficient Python implementation for microcontrollers and constrained systems.

grade: devel
confinement: devmode

apps:
    micropython:
        command: bin/micropython

parts:
    micropython:
        plugin: nil
        source: https://github.com/micropython/micropython/releases/download/v1.9.4/micropython-1.9.4.tar.gz
        source-type: tar
        override-build: |
          cd ports/unix
          make axtls && make
          mkdir $SNAPCRAFT_PART_INSTALL/bin
          cp micropython $SNAPCRAFT_PART_INSTALL/bin
        prime:
          - bin
