name: micropython
version: "1.27.0"
summary: MicroPython linux version
description: |
  MicroPython is a lean and efficient Python implementation for microcontrollers and constrained systems.

base: core24
confinement: strict
grade: stable

apps:
  micropython:
    command: usr/local/bin/micropython
    plugs:
      - home
      - network

build-packages:
  - build-essential
  - libffi-dev
  - pkg-config

parts:
  micropython:
    after:
      - patches
    plugin: make
    source: https://github.com/micropython/micropython/releases/download/v1.27.0/micropython-1.27.0.tar.xz
    source-subdir: ports/unix
    source-type: tar
  patches:
    source: patches
    plugin: dump
    prime:
      - -*
  desktop:
    plugin: dump
    source: snap/gui
