name: micropython
version: "1.11"
summary: MicroPython Unix port
description: |
  MicroPython is a lean and efficient Python implementation for microcontrollers and constrained systems.

base: core18
confinement: strict
grade: stable

apps:
  micropython:
    command: usr/local/bin/micropython
    plugs:
      - home
      - network

build-packages:
  - build-essential
  - libffi-dev
  - pkg-config

parts:
  micropython:
    plugin: make
    source: https://github.com/micropython/micropython/releases/download/v1.11/micropython-1.11.tar.gz
    source-subdir: ports/unix
    source-type: tar
